// markdown_api_extractor — 解析"全量接口索引"表，直接产 registry/seed/api_index_seed.json
// 全字段（seq/module/name/method/path/issue_marker/api_id/domain/capability/lifecycle_status/quality_score_seed）。
//
// 之前 api_index_seed.json 由外部 Python 维护；现在彻底吸纳进 ts，rebuild 链可端到端再生。
//
// CLI:
//   node --import ./scripts/ts_loader.mjs src/extractors/markdown_api_extractor.ts \
//     [<input.md>] [<output.json>]

import fs from "node:fs";
import path from "node:path";
import { canonicalizePath, pathToApiId } from "../normalizers/path_canon.js";
import { inferDomainV2 } from "../normalizers/domain_mapper.js";

export type ApiIndexRow = {
  seq: number;
  module: string;
  name: string;
  method: string;
  path: string;
  issue_marker: string;
  domain: string;
  capability?: string;
  lifecycle_status: "candidate" | "blocked";
  quality_score_seed: number;
  api_id: string;
};

const ROW_RE =
  /^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*(GET|POST|PUT|DELETE|PATCH)\s*\|\s*`([^`]+)`\s*\|\s*([^|]*)\|\s*$/;

export function parseApiIndex(markdown: string): ApiIndexRow[] {
  const rows: ApiIndexRow[] = [];
  for (const line of markdown.split(/\r?\n/)) {
    const m = line.match(ROW_RE);
    if (!m) continue;

    const seq = Number(m[1]);
    const module = m[2]!.trim();
    const name = m[3]!.trim();
    const method = m[4]!.trim();
    const rawPath = m[5]!.trim();
    const issueMarker = m[6]!.trim();

    const canon = canonicalizePath(rawPath);
    const apiId = pathToApiId(canon.path);

    const dm = inferDomainV2({ name, module, path: canon.path });
    const placeholder = canon.placeholder;
    const lifecycle: ApiIndexRow["lifecycle_status"] = placeholder ? "blocked" : "candidate";

    let qSeed = 0.7;
    if (issueMarker) qSeed -= 0.15;
    if (placeholder) qSeed -= 0.2;
    if (dm.domain === "未分类域") qSeed -= 0.05;
    qSeed = Math.max(0.2, Math.min(0.9, Number(qSeed.toFixed(2))));

    rows.push({
      seq,
      module,
      name,
      method,
      path: canon.path,
      issue_marker: issueMarker,
      domain: dm.domain,
      capability: dm.capability,
      lifecycle_status: lifecycle,
      quality_score_seed: qSeed,
      api_id: apiId,
    });
  }
  return rows;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const ROOT = process.cwd();
  const input = process.argv[2] ?? "sources/api_docs/智能体数仓完整接口文档_整理版.md";
  const output = process.argv[3] ?? "registry/seed/api_index_seed.json";

  const md = fs.readFileSync(input, "utf-8");
  const rows = parseApiIndex(md);
  fs.mkdirSync(path.dirname(path.resolve(ROOT, output)), { recursive: true });

  const payload = {
    source: input,
    generated_at: new Date().toISOString(),
    generator: "markdown_api_extractor.ts",
    note: "regenerated by extract:index; do not hand-edit. tweak rules in src/normalizers/domain_mapper.ts or registry/domain_mapping.locked.yaml",
    count: rows.length,
    apis: rows,
  };
  fs.writeFileSync(output, JSON.stringify(payload, null, 2));

  const byStatus: Record<string, number> = {};
  const byDomain: Record<string, number> = {};
  for (const r of rows) {
    byStatus[r.lifecycle_status] = (byStatus[r.lifecycle_status] ?? 0) + 1;
    byDomain[r.domain] = (byDomain[r.domain] ?? 0) + 1;
  }
  console.log(`[extract:index] ${rows.length} rows -> ${output}`);
  console.log(JSON.stringify({ byStatus, byDomain }, null, 2));
}